module.exports = {
  en: {
    // Shared
    dashboard: 'Dashboard',
    appointments: 'Appointments',
    customers: 'Customers',
    vehicles: 'Vehicles',
    repairs: 'Repairs',
    inventory: 'Inventory',
    billing: 'Billing',
    staff: 'Users & Staff',
    activityLogs: 'System Logs',
    welcome: 'Welcome back',
    dashboardSubtitle: "here's what's happening at your garage today.",
    totalRevenue: 'Total Revenue',
    activeRepairs: 'Active Repairs',
    totalCustomers: 'Total Customers',
    lowStockAlerts: 'Low Stock Alerts',
    recentRepairs: 'Recent Repairs',
    inventoryAlerts: 'Inventory Alerts',
    searchPlaceholder: 'Search...',
    resetData: 'Reset Data',
    newRepairOrder: 'New Repair Order',
    viewAll: 'View All',
    manageStock: 'Manage Stock',
    reorder: 'Reorder',
    noItemsLowStock: 'No items are low on stock.',
    vehicle: 'Vehicle',
    customer: 'Customer',
    dateIn: 'Date In',
    date: 'Date',
    status: 'Status',
    admin: 'Admin User',
    administrator: 'Administrator',
    language: 'Language',
    amharic: 'አማርኛ',
    english: 'English',
    add: 'Add',
    edit: 'Edit',
    deleteBtn: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    actions: 'Actions',
    name: 'Name',
    phone: 'Phone',
    address: 'Address',
    email: 'Email',
    plate: 'Plate',
    make: 'Make',
    model: 'Model',
    year: 'Year',
    owner: 'Owner',
    notes: 'Notes',
    quantity: 'Quantity',
    price: 'Price',
    total: 'Total',
    search: 'Search',
    
    // Appointments
    bookAppointment: 'Book Appointment',
    selectCustomer: 'Select Customer',
    selectVehicle: 'Select Vehicle',
    reason: 'Reason',
    time: 'Time',
    scheduled: 'Scheduled',
    arrived: 'Arrived',
    cancelled: 'Cancelled',
    today: 'Today',
    nextDay: 'Next Day',
    prevDay: 'Previous Day',
    noAppointments: 'No Appointments',
    requested: 'Requested',
    approve: 'Approve',
    reject: 'Reject',
    reschedule: 'Reschedule',
    rescheduled: 'Rescheduled',
    appointmentStatusChanged: 'Appointment Status Updated',
    appointmentApproved: 'Your appointment has been approved!',
    appointmentRejected: 'Your appointment request was declined.',
    appointmentRescheduled: 'Your appointment has been rescheduled.',

    // Repairs
    pending: 'Pending',
    inProgress: 'In Progress',
    completed: 'Completed',
    mechanic: 'Mechanic',
    laborCost: 'Labor Cost',
    parts: 'Parts',
    addPart: 'Add Part',

    // Billing
    invoices: 'Invoices',
    invoiceId: 'Invoice ID',
    paymentStatus: 'Payment Status',
    paid: 'Paid',
    subtotal: 'Subtotal',
    tax: 'Tax',
    print: 'Print',
    downloadPDF: 'Download PDF',
    billTo: 'Bill To',
    received: 'Payment Received',
    invoiceDate: 'Invoice Date',
    dueDate: 'Due Date',
    labor: 'Labor',
    additionalCharges: 'Additional Charges',
    discount: 'Discount',
    grandTotal: 'Grand Total',
    unpaid: 'Unpaid',
    partial: 'Partially Paid',
    paidStatus: 'Paid',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    bankTransfer: 'Bank Transfer',
    mobileBanking: 'Mobile Banking',
    telebirr: 'Telebirr',
    cbeBirr: 'CBE Birr',
    awashBirr: 'Awash Birr',
    mPesa: 'M-Pesa',
    card: 'Credit/Debit Card',
    other: 'Other',
    currency: 'Currency',
    etb: 'Ethiopian Birr',
    usd: 'US Dollar',
    eur: 'Euro',
    gbp: 'British Pound',
    aed: 'UAE Dirham',
    sar: 'Saudi Riyal',
    paymentSettings: 'Payment Settings',
    paymentConfirmed: 'Payment Confirmed',
    paymentRejected: 'Payment Rejected',
    receipt: 'Receipt',
    invoice: 'Invoice',
    addAccount: 'Add Account',
    bankName: 'Bank Name',
    accountHolder: 'Account Holder',
    accountNumber: 'Account Number',
    branch: 'Branch',
    phonePayment: 'Phone Payment',
    receiverName: 'Receiver Name',
    appType: 'App Type',
    markedDefault: 'Default',
    payNow: 'Pay Now',
    paymentInstructions: 'Payment Instructions',
    uploadProof: 'Upload Proof',
    transactionId: 'Transaction ID',
    screenshot: 'Screenshot / Receipt',
    submitConfirmation: 'Submit Confirmation',
    pendingApproval: 'Pending Approval',
    approved: 'Approved',
    rejected: 'Rejected',
    financialReports: 'Financial Reports',
    incomeDay: 'Daily Income',
    incomeWeek: 'Weekly Income',
    incomeMonth: 'Monthly Income',
    revenueByMethod: 'Revenue by Method',
    goToDashboard: 'Go to Dashboard',
    searchGaragePlaceholder: 'Search by name or ID...',
    noGaragesFound: 'No garages found matching your search.',
    homeLanding: 'Home',

    // Staff
    employee: 'Employee',
    addEmployee: 'Add Employee',
    role: 'Role',
    receptionist: 'Receptionist',
    cashier: 'Cashier',
    storekeeper: 'Storekeeper',
    manager: 'Manager',
    inventoryManager: 'Inventory Manager',
    active: 'Active',
    inactive: 'Inactive',
    signIn: 'Sign In',
    createAccount: 'Create Account',
    emailOrPhone: 'Email or Phone Number',
    loginSubtitle: 'Welcome back! Sign in with your email or phone.',
    signupSubtitle: 'Join our garage management system.',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    passwordMinChar: 'Password must be at least 6 characters.',
    provideEmailOrPhone: 'Please provide either an email or a phone number.',
    garageName: 'Garage Name',
    selectGarage: 'Select Garage',
    confirmPassword: 'Confirm Password',
    oldPassword: 'Current Password',
    passwordsDoNotMatch: 'Passwords do not match.',
    currentPasswordIncorrect: 'Current password is incorrect.',
    oldPasswordRequired: 'Please enter your current password to set a new one.',
    chat: 'Chat',
    search_contacts: 'Search contacts...',
    no_contacts_found: 'No contacts found.',
    back_to_contacts: 'Back to Contacts',
    no_messages_yet: 'No messages yet',
    start_conversation: 'Start a conversation',
    type_message: 'Type a message...',
    newJobAssigned: 'New Job Assigned',
    repairInProgress: 'Repair In Progress',
    repairCompleted: 'Repair Completed',
    acceptJob: 'Accept Job',
    declineJob: 'Decline Job',
    
    // Confirmations
    areYouSure: 'Are you sure?',
    confirmDeleteRepair: 'Permanently delete this repair order?',
    confirmDeleteCustomer: 'Remove this customer and their history?',
    confirmDeleteVehicle: 'Delete this vehicle and its maintenance records?',
    confirmDeleteInventory: 'Remove this item from inventory?',
    confirmDeleteStaff: 'Revoke access for this staff member?',
    confirmDeleteAppointment: 'Cancel and delete this appointment?',
    confirmDeleteMessage: 'Remove this message from chat?',
    landingHome: "Home", landingAbout: "About", landingServices: "Services", landingFeatures: "Features",
    landingLogin: "Login", landingGetStarted: "Get Started", landingCta: "Start Free Trial", landingExplore: "Explore Services",
    heroTitle1: "Modernize Your ", heroTitle2: "Garage Operations",
    heroSubtitle: "The all-in-one comprehensive platform for mechanics, inventory managers, and administrators to streamline end-to-end vehicle repairs, map real-time roadside assistance, and automate spare parts management.",
    aboutTitle: "About Us (Our Definition)", aboutSubtitle: "Systematizing auto repair shop management.",
    aboutP1: "Definition of GarageSys: We are a digital ecosystem that bridges the communication gap between mechanics, inventory managers, administrators, and customers. We replace paper-based chaos with structured, accountable digital workflows.",
    aboutP2: "Whether you are tracking a fleet of roadside assistance vehicles via live maps, managing an extensive inventory of spare parts with low-stock alerts, or issuing automated status updates to anxious car owners—our infrastructure gives you the precise tools needed for modern mechanical success.",
    servicesTitle: "Our Services", servicesSubtitle: "Comprehensive auto repair and maintenance solutions.",
    srv1Title: "Digital Diagnostics", srv1Desc: "Advanced computer diagnostics pinpointing complex engine and electrical issues with absolute precision.",
    srv2Title: "Fluid & Preventative", srv2Desc: "Premium synthetic fluid flushes and preventative maintenance schedules engineered to maximize vehicle longevity.",
    srv3Title: "Brake & ABS Services", srv3Desc: "Comprehensive safety overhauls utilizing high-friction ceramic pads, rotor resurfacing, and electronic ABS diagnostics.",
    srv4Title: "Steering & Suspension", srv4Desc: "Precision laser wheel alignment, strut replacement, and complete suspension servicing for a flawlessly smooth ride.",
    srv5Title: "Climate Control", srv5Desc: "Complete A/C system evacuation, refrigerant recharge, and compressor diagnostics to ensure optimal cabin temperature.",
    srv6Title: "Transmission Systems", srv6Desc: "Expert electronic transmission diagnostics, clutch repairs, and comprehensive mechanical rebuilds by certified specialists.",
    featuresTitle: "Everything You Need", featuresSubtitle: "Powerful tools designed specifically for modern auto repair shops.",
    feat1Title: "Live Map Tracking", feat1Desc: "Track roadside assistance vehicles in real-time and provide accurate ETAs to customers.",
    feat2Title: "Inventory Management", feat2Desc: "Keep track of spare parts, receive low-stock alerts, and manage supplier orders with ease.",
    feat3Title: "Role-Based Access", feat3Desc: "Secure system with specific views for Admins, Mechanics, Inventory Managers, and Customers.",
    feat4Title: "Repair Tracking", feat4Desc: "Log vehicle issues, assign mechanics, and update repair statuses from intake to completion.",
    contactTitle: "Get In Touch", contactSubtitle: "Have questions? Need a custom plan? Contact our team.",
    contactName: "Full Name", contactPhone: "Phone Number", contactMsg: "Message", contactPlaceholder: "Tell us about the issue or how we can help modernize your operations...", contactSendBtn: "Send Message",
    landingFooterText: "GarageSys. All rights reserved.",
    
    // Material Management
    materialRequests: 'Material Requests',
    requestMaterials: 'Request Materials',
    activeRequests: 'Active Requests',
    preparedPickup: 'Prepared for Pickup',
    readyForPickup: 'Ready for Pickup',
    pickedUp: 'Picked Up',
    insufficientStock: 'Insufficient Stock',
    partiallyApproved: 'Partially Approved',
    issuedBy: 'Issued By',
    pickedUpBy: 'Picked Up By',
    approvedQty: 'Approved Qty',
    requestedQty: 'Requested Qty',
    issuedQty: 'Issued Qty',
    materialIssued: 'Material Issued',
    materialRequestApproved: 'Material Request Approved',
    materialRequestRejected: 'Material Request Rejected',
    insufficientStockNotice: 'Insufficient Stock Notice',
    billable: 'Billable',
    notBillable: 'Not Billable',
    paymentUnpaid: 'Unpaid',
    paymentPartiallyPaid: 'Partially Paid',
    paymentPaid: 'Paid',
    searchRequests: 'Search requests...',
    allMechanics: 'All Mechanics',
    allStatuses: 'All Statuses',
    confirmPickup: 'Confirm Pickup',
    editRequest: 'Edit Request',
    reviewRequest: 'Review Request',
    lowStock: 'Low Stock',
    ordered: 'Ordered from Supplier',
    inTransit: 'In Transit',
    delayed: 'Delayed',
    waitingForParts: 'Waiting for Parts',
  },
  am: {
    // Shared
    dashboard: 'ዳሽቦርድ',
    appointments: 'ቀጠሮዎች',
    customers: 'ደንበኞች',
    vehicles: 'ተሽከርካሪዎች',
    repairs: 'ጥገናዎች',
    inventory: 'ዕቃዎች',
    billing: 'ክፍያ',
    staff: 'ተጠቃሚዎች',
    activityLogs: 'የስርዓት መዝገቦች',
    welcome: 'እንኳን ደህና መጡ',
    dashboardSubtitle: 'በዛሬው እለት በጋራዥዎ ውስጥ እየተከናወኑ ያሉ ነገሮች።',
    totalRevenue: 'ጠቅላላ ገቢ',
    activeRepairs: 'በሂደት ላይ ያሉ ጥገናዎች',
    totalCustomers: 'ጠቅላላ ደንበኞች',
    lowStockAlerts: 'አነስተኛ ክምችት ማስጠንቀቂያዎች',
    recentRepairs: 'የቅርብ ጊዜ ጥገናዎች',
    inventoryAlerts: 'የዕቃዎች ማስጠንቀቂያ',
    searchPlaceholder: 'ይፈልጉ...',
    resetData: 'መረጃ አጥፋ',
    newRepairOrder: 'አዲስ የጥገና ትዕዛዝ',
    viewAll: 'ሁሉንም ተመልከት',
    manageStock: 'ዕቃዎችን አስተካክል',
    reorder: 'እንደገና እዘዝ',
    noItemsLowStock: 'ምንም የሚያልቅ ዕቃ የለም።',
    vehicle: 'ተሽከርካሪ',
    customer: 'ደንበኛ',
    dateIn: 'የገባበት ቀን',
    date: 'ቀን',
    status: 'ሁኔታ',
    admin: 'አስተዳዳሪ',
    administrator: 'ዋና አስተዳዳሪ',
    status_pending: 'በመጠበቅ ላይ',
    status_progress: 'በመከናወን ላይ',
    status_completed: 'ተጠናቋል',
    language: 'ቋንቋ',
    amharic: 'አማርኛ',
    english: 'English',
    add: 'ጨምር',
    edit: 'አስተካክል',
    deleteBtn: 'አጥፋ',
    save: 'መዝግብ',
    cancel: 'ተው',
    actions: 'ድርጊቶች',
    name: 'ስም',
    phone: 'ስልክ',
    address: 'አድራሻ',
    email: 'ኢሜይል',
    plate: 'ሰሌዳ',
    make: 'ምርት',
    model: 'ሞዴል',
    year: 'ዓ.ም',
    owner: 'ባለቤት',
    notes: 'ማስታወሻ',
    quantity: 'ብዛት',
    price: 'ዋጋ',
    total: 'ጠቅላላ',
    search: 'ፈልግ',

    // Appointments
    bookAppointment: 'ቀጠሮ ያዝ',
    selectCustomer: 'ደንበኛ ይምረጡ',
    selectVehicle: 'ተሽከርካሪ ይምረጡ',
    reason: 'ምክንያት',
    time: 'ሰዓት',
    scheduled: 'የተያዘ',
    arrived: 'የመጣ',
    cancelled: 'የተሰረዘ',
    today: 'ዛሬ',
    nextDay: 'ቀጣይ ቀን',
    prevDay: 'ያለፈው ቀን',
    noAppointments: 'ምንም ቀጠሮ የለም',
    requested: 'የተጠየቀ',
    approve: 'አጽድቅ',
    reject: 'ውድቅ አድርግ',
    reschedule: 'ጊዜ ቀይር',
    rescheduled: 'ጊዜው የተቀየረ',
    appointmentStatusChanged: 'የቀጠሮ ሁኔታ ተቀይሯል',
    appointmentApproved: 'ቀጠሮዎ ጸድቋል!',
    appointmentRejected: 'የቀጠሮ ጥያቄዎ ውድቅ ተደርጓል።',
    appointmentRescheduled: 'የቀጠሮዎ ጊዜ ተቀይሯል።',

    // Repairs
    pending: 'የሚጠበቅ',
    inProgress: 'በሂደት ላይ',
    completed: 'ተጠናቋል',
    mechanic: 'መካኒክ',
    laborCost: 'የጉልበት ዋጋ',
    parts: 'መለዋወጫዎች',
    addPart: 'መለዋወጫ ጨምር',

    // Billing
    invoices: 'ደረሰኞች',
    invoiceId: 'የደረሰኝ መለያ',
    paymentStatus: 'የክፍያ ሁኔታ',
    paid: 'ተከፍሏል',
    subtotal: 'መነሻ ድምር',
    tax: 'ታክስ',
    print: 'አትም',
    downloadPDF: 'PDF አውርድ',
    billTo: 'ለ...',
    received: 'ክፍያ ተቀብለናል',
    invoiceDate: 'የደረሰኝ ቀን',
    dueDate: 'የመክፈያ ቀን',
    labor: 'የጉልበት ሥራ',
    additionalCharges: 'ተጨማሪ ክፍያዎች',
    discount: 'ቅናሽ',
    grandTotal: 'ጠቅላላ ድምር',
    unpaid: 'ያልተከፈለ',
    partial: 'በከፊል የተከፈለ',
    paidStatus: 'የተከፈለ',
    paymentMethod: 'የክፍያ መንገድ',
    cash: 'ጥሬ ገንዘብ',
    bankTransfer: 'የባንክ ዝውውር',
    mobileBanking: 'የሞባይል ባንክ',
    telebirr: 'ቴሌብር',
    cbeBirr: 'ሲቢኢ ብር',
    awashBirr: 'አዋሽ ብር',
    mPesa: 'ኤም-ፔሳ',
    card: 'ክሬዲት/ዴቢት ካርድ',
    other: 'ሌላ',
    currency: 'ምንዛሬ',
    etb: 'የኢትዮጵያ ብር',
    usd: 'የአሜሪካ ዶላር',
    eur: 'ዩሮ',
    gbp: 'የእንግሊዝ ፓውንድ',
    aed: 'የተባበሩት አረብ ኤምሬትስ ድርሃም',
    sar: 'የሳውዲ ሪያል',
    paymentSettings: 'የክፍያ ቅንብሮች',
    paymentConfirmed: 'ክፍያ ተረጋግጧል',
    paymentRejected: 'ክፍያ ውድቅ ተደርጓል',
    receipt: 'ደረሰኝ',
    invoice: 'ደረሰኝ',
    addAccount: 'መለያ ጨምር',
    bankName: 'የባንክ ስም',
    accountHolder: 'የሂሳብ ባለቤት ስም',
    accountNumber: 'የሂሳብ ቁጥር',
    branch: 'ቅርንጫፍ',
    phonePayment: 'የስልክ ክፍያ',
    receiverName: 'ተቀባይ ስም',
    appType: 'የመተግበሪያ አይነት',
    markedDefault: 'ዋና',
    payNow: 'አሁን ይክፈሉ',
    paymentInstructions: 'የክፍያ መመሪያዎች',
    uploadProof: 'የክፍያ ማረጋገጫ ይላኩ',
    transactionId: 'የግብይት መለያ (Transaction ID)',
    screenshot: 'የክፍያ ደረሰኝ/ፎቶ',
    submitConfirmation: 'ማረጋገጫ ላክ',
    pendingApproval: 'በመጠባበቅ ላይ',
    approved: 'ጸድቋል',
    rejected: 'ውድቅ ተደርጓል',
    financialReports: 'የፋይናንስ ሪፖርቶች',
    incomeDay: 'የዕለቱ ገቢ',
    incomeWeek: 'የሳምንቱ ገቢ',
    incomeMonth: 'የወሩ ገቢ',
    revenueByMethod: 'ገቢ በክፍያ መንገድ',
    goToDashboard: 'ወደ ዳሽቦርድ ሂድ',
    searchGaragePlaceholder: 'በስም ወይም በመለያ ይፈልጉ...',
    noGaragesFound: 'ምንም ጋራዥ አልተገኘም።',
    homeLanding: 'ዋና ገጽ',

    // Staff
    employee: 'ሰራተኛ',
    addEmployee: 'ሰራተኛ ጨምር',
    role: 'ሃላፊነት',
    receptionist: 'አስተናጋጅ',
    cashier: 'ሂሳብ ሰራተኛ',
    storekeeper: 'መጋዘን ሰራተኛ',
    manager: 'ሥራ አስኪያጅ',
    inventoryManager: 'የዕቃ አስተዳዳሪ',
    active: 'ገባሪ',
    inactive: 'ያልነቃ',
    signIn: 'ግባ',
    createAccount: 'መለያ ፍጠር',
    emailOrPhone: 'ኢሜይል ወይም ስልክ ቁጥር',
    loginSubtitle: 'እንኳን ደህና መጡ! በኢሜይልዎ ወይም በስልክ ቁጥርዎ ይግቡ።',
    signupSubtitle: 'የጋራዥ ማኔጅመንት ስርዓታችንን ይቀላቀሉ።',
    alreadyHaveAccount: 'ቀደም ብለው መለያ አለዎት?',
    dontHaveAccount: 'መለያ የለዎትም?',
    passwordMinChar: 'የይለፍ ቃል ቢያንስ 6 ፊደላት መሆን አለበት።',
    provideEmailOrPhone: 'እባክዎን ኢሜይል ወይም ስልክ ቁጥር ያስገቡ።',
    garageName: 'የጋራዥ ስም',
    selectGarage: 'ጋራዥ ይምረጡ',
    confirmPassword: 'የይለፍ ቃል ያረጋግጡ',
    oldPassword: 'የአሁኑ የይለፍ ቃል',
    passwordsDoNotMatch: 'የይለፍ ቃላት አይዛመዱም።',
    currentPasswordIncorrect: 'የአሁኑ የይለፍ ቃል ትክክል አይደለም።',
    oldPasswordRequired: 'አዲስ የይለፍ ቃል ለመቀየር እባክዎ የአሁኑን የይለፍ ቃል ያስገቡ።',
    chat: 'ጭውውት',
    search_contacts: 'ሰዎችን ይፈልጉ...',
    no_contacts_found: 'ምንም ሰው አልተገኘም።',
    back_to_contacts: 'ወደ ሰዎቹ ዝርዝር ይመለሱ',
    no_messages_yet: 'ምንም መልእክት የለም',
    start_conversation: 'ጭውውት ይጀምሩ',
    type_message: 'መልእክት ይጻፉ...',
    newJobAssigned: 'አዲስ ስራ ተመድቧል',
    repairInProgress: 'ጥገና በሂደት ላይ',
    repairCompleted: 'ጥገና ተጠናቋል',
    acceptJob: 'ስራውን ተቀበል',
    declineJob: 'ስራውን አልፈልግም',
    
    // Confirmations
    areYouSure: 'እርግጠኛ ነዎት?',
    confirmDeleteRepair: 'ይህን የጥገና ትዕዛዝ በቋሚነት ያጥፉ?',
    confirmDeleteCustomer: 'ይህንን ደንበኛ እና ታሪካቸውን ያስወግዱ?',
    confirmDeleteVehicle: 'ይህንን ተሽከርካሪ እና የጥገና መዝገቦቹን ያጥፉ?',
    confirmDeleteInventory: 'ይህንን እቃ ከክምችት ያስወግዱ?',
    confirmDeleteStaff: 'ለዚህ ሰራተኛ መዳረሻን ይሰርዙ?',
    confirmDeleteAppointment: 'ይህንን ቀጠሮ ይሰርዙ?',
    confirmDeleteMessage: 'ይህንን መልእክት ከውይይቱ ያስወግዱ?',
    landingHome: "መነሻ ገጽ", landingAbout: "ስለ እኛ", landingServices: "አገልግሎቶቻችን", landingFeatures: "ዋና ባህሪዎች",
    landingLogin: "ግባ", landingGetStarted: "አሁን ጀምር", landingCta: "ነፃ ሙከራ ጀምር", landingExplore: "አገልግሎቶቻችንን ያስሱ",
    heroTitle1: "የጋራዥዎን አሠራር ", heroTitle2: "ዘመናዊ ያድርጉ",
    heroSubtitle: "ለሜካኒኮች፣ ለእቃ አስተዳዳሪዎች እና ለአስተዳዳሪዎች — የተሽከርካሪ ጥገናን ለማፋጠን፣ የጎዳና ላይ እርዳታን በካርታ ለመከታተል እና የመለዋወጫ ዕቃ አስተዳደርን በራስ-ሰር ለማካሄድ የሚያስችል ሁሉ-በ-አንድ መድረክ።",
    aboutTitle: "ስለ እኛ — ትርጓሜያችን", aboutSubtitle: "የመኪና ጥገና ድርጅቶችን አሠራር ዲጂታይዝ እናደርጋለን።",
    aboutP1: "GarageSys ምንድነው፡- በሜካኒኮች፣ በዕቃ አስተዳዳሪዎች፣ በአስተዳዳሪዎች እና በደንበኞች መካከል ያለውን የግንኙነት ክፍተት ለማጥበብ የተነደፈ ዲጂታል ሥርዓት ነን። በወረቀት ላይ የሚደረገውን የዘፈቀደ አሠራር ወደ ተደራጀ እና ተጠያቂነት ያለው ዲጂታል የሥራ ፍሰት እንቀይረዋለን።",
    aboutP2: "የጎዳና ላይ እርዳታ ተሽከርካሪዎችን በቀጥታ ካርታ ሲከታተሉ፣ ሰፊ ቋት ያለው የመለዋወጫ እቃ ቆጠራ ሲያስተዳድሩ፣ ወይም ለጭንቅ ውስጥ ላሉ የተሽከርካሪ ባለቤቶች ራስ-ሰር የሁኔታ ዝምና ሲያቀርቡ — መሠረተ ልማታችን ለዘመናዊ ሜካኒካዊ ስኬት የሚያስፈልጉዎትን ትክክለኛ መሣሪያዎች ይሰጥዎታል።",
    servicesTitle: "አገልግሎቶቻችን", servicesSubtitle: "ሁሉን-አቀፍ የተሽከርካሪ ጥገና እና ክብካቤ መፍትሔዎች።",
    srv1Title: "ዲጂታል ምርመራ", srv1Desc: "ውስብስብ የሞተር እና የኤሌክትሪክ ስሕተቶችን በትክክል ለማወቅ የሚያስችል ዘመናዊ የኮምፒዩተር ምርመራ አገልግሎት።",
    srv2Title: "ፈሳሽ ቅያሪ እና ጥንቃቄያዊ ጥገና", srv2Desc: "የተሽከርካሪን ዕድሜ ለማራዘም የሚያስችሉ ከፍተኛ ጥራት ያላቸው ሰው ሰራሽ ዘይቶች ቅያሪ እና መደበኛ የጥገና ሰሌዳ።",
    srv3Title: "ብሬክ እና ABS አገልግሎት", srv3Desc: "ከፍተኛ ጥራት ያላቸው ሴራሚክ ብሬክ ፓድ፣ ሮተር ማጠናቀቅ እና ኤሌክትሮኒክ ABS ምርመራን የሚያካትት አጠቃላይ የደህንነት ጥገና።",
    srv4Title: "ስቲያሪንግ እና ሰስፔንሽን", srv4Desc: "ትክክለኛ የሌዘር ጎማ ሚዛን፣ የሾክ አብሾርበር ቅያሪ እና ለስላሳ ጉዞ የሚሰጥ ሙሉ የሰስፔንሽን አገልግሎት።",
    srv5Title: "የአየር ማቀዝቀዣ ስርዓት", srv5Desc: "ሙሉ የ AC ሲስተም ፍሰሰ፣ ሪፍሪጀራንት ሙሌት እና ምቹ የቤት ውስጥ ሙቀት ለማረጋገጥ የሚሠራ የኮምፕሬሰር ምርመራ።",
    srv6Title: "ትራንስሚሽን ስርዓቶች", srv6Desc: "የኤሌክትሮኒክ ስርጭት ምርመራ፣ ክላቸ ጥገና እና የምስጥር ባለሙያዎቻችን የሚያከናውኑት ሙሉ ሜካኒካዊ ዕድሳት።",
    featuresTitle: "የሚፈልጉት ሁሉ እዚህ ይገኛል", featuresSubtitle: "ለዘመናዊ የመኪና ጥገና ድርጅቶች በተለይ የተነደፉ ኃይለኛ የዲጂታል መሣሪያዎች።",
    feat1Title: "በቀጥታ ካርታ ክትትል", feat1Desc: "የጎዳና ላይ እርዳታ ተሽከርካሪዎችን ወዲያውኑ ይከታተሉ እና ለደንበኞች ትክክለኛ የደረሻ ሰዓት ያቅርቡ።",
    feat2Title: "የእቃ ቆጠራ አስተዳደር", feat2Desc: "የመለዋወጫ ዕቃዎችን ቁጥር ይከታተሉ፣ ዝቅተኛ ቋት ሲደርስ ማንቂያ ይቀበሉ፣ እና የአቅራቢ ትዕዛዞችን በቀላሉ ያስተዳድሩ።",
    feat3Title: "ሚና-ተኮር የስርዓት ፍቃድ", feat3Desc: "ለአስተዳዳሪዎች፣ ሜካኒኮች፣ የዕቃ አስተዳዳሪዎች እና ደንበኞች ልዩ ልዩ የደህንነት ደረጃ ያለው ስርዓት።",
    feat4Title: "የጥገና ሂደት ክትትል", feat4Desc: "የተሽከርካሪ ጉድለቶችን ይምዝግቡ፣ ሜካኒኮችን ይመድቡ፣ እና ከመቀበያ እስከ ማጠናቀቂያ ሁሉ ሁኔታ ያዘምኑ።",
    contactTitle: "ያግኙን", contactSubtitle: "ጥያቄ አለዎት? ብጁ እቅድ ይፈልጋሉ? ቡድናችን ለማገልገል ዝግጁ ነው።",
    contactName: "ሙሉ ስም", contactPhone: "ስልክ ቁጥር", contactMsg: "መልዕክት", contactPlaceholder: "ያጋጠምዎትን ችግር ወይም ሥርዓቱን እንዴት እንዲያዘምኑ እናግዝ ስለሚሉበት ሁኔታ ይነግሩን...", contactSendBtn: "መልዕክት ላክ",
    landingFooterText: "GarageSys. መብቱ በሕግ የተጠበቀ ነው።",

    // Material Management
    materialRequests: 'የእቃ ጥያቄዎች',
    requestMaterials: 'እቃ እዘዝ',
    activeRequests: 'ንቁ ጥያቄዎች',
    preparedPickup: 'ለመረከብ የተዘጋጀ',
    readyForPickup: 'ለመረከብ ዝግጁ',
    pickedUp: 'ተረክቧል',
    insufficientStock: 'በቂ ክምችት የለም',
    partiallyApproved: 'በከፊል የጸደቀ',
    issuedBy: 'የሰጠው ሰራተኛ',
    pickedUpBy: 'የተረከበው ሰራተኛ',
    approvedQty: 'የጸደቀ ብዛት',
    requestedQty: 'የተጠየቀ ብዛት',
    issuedQty: 'የተሰጠ ብዛት',
    materialIssued: 'እቃ ተሰጥቷል',
    materialRequestApproved: 'የእቃ ጥያቄ ጸድቋል',
    materialRequestRejected: 'የእቃ ጥያቄ ውድቅ ተደርጓል',
    insufficientStockNotice: 'የክምችት እጥረት ማሳሰቢያ',
    billable: 'የሚከፈልበት',
    notBillable: 'የማይከፈልበት',
    paymentUnpaid: 'ያልተከፈለ',
    paymentPartiallyPaid: 'በከፊል የተከፈለ',
    paymentPaid: 'ተከፍሏል',
    searchRequests: 'ጥያቄዎችን ይፈልጉ...',
    allMechanics: 'ሁሉም መካኒኮች',
    allStatuses: 'ሁሉም ሁኔታዎች',
    confirmPickup: 'ርክክብ አረጋግጥ',
    editRequest: 'ጥያቄ አስተካክል',
    reviewRequest: 'ጥያቄውን መርምር',
    lowStock: 'አነስተኛ ክምችት',
    ordered: 'ከአቅራቢ የታዘዘ',
    inTransit: 'በመንገድ ላይ',
    delayed: 'የዘገየ',
    waitingForParts: 'መለዋወጫ በመጠባበቅ ላይ',
  }
};